### ISSUE TITLE
CSSConfig: searchDirs parameter not working. 

### ISSUE THREAD

**Issue by sellajad** [oleg-shilo/cs-script.vscode#10]
Updates after 1.4.0 have affected the searchDirs parameter in Engine Settings. This parameter does not seem to be working in later releases. Direct references to the directories and objects need to be put in to bypass the issue.

**Comment by sellajad** [comment]
I can edit the following file instead to get another workaround C:\Users\USER\AppData\Roaming\Code\User\cs-script.user\css_config.xml

**Comment by oleg-shilo** [comment]
Can you please have a look at your settings. Most likely you have `cs-script.dotnet_run_host_on_win` enabled.
![image](https://user-images.githubusercontent.com/16729806/40030171-69adf142-582c-11e8-92bc-966b019b047c.png)

If it is the case then during the run the extension uses .NET runtime instead of Mono when hosted on Windows. And since .NET and Mono require slightly different settings they are controlled by the two different settings files: `css_config.xml` vs. `css_config.mono.xml`.

The settings file probing rules are simple. If only `css_config.xml` file is present then it is used for both runtimes .NET and Mono. And if `css_config.xml` and `css_config.mono.xml` files are present then the first is used under .NET and the second one under Mono.

To make it more obvious I have changed the "CS-Script: Engine Settings" command to open both files for editing:

![image](https://user-images.githubusercontent.com/16729806/40031372-c5dd7d10-5832-11e8-86d7-5e852db2a71d.png)

The description of the `cs-script.dotnet_run_host_on_win` has also been improved to indicate that an alternative setting file is to be used at runtime.

The fix will be available in the very next release.

**Comment by oleg-shilo** [comment]
OK, I found that it was a typo in the `package.json` that always makes `cs-script.dotnet_run_host_on_win` true.

The fix is on the way.

**Comment by oleg-shilo** [comment]
Done.

**Comment by sellajad** [comment]
Thank you very much for responding so quickly to this. Great job and great software.
