### ISSUE TITLE
How to get intellisense to work?

### ISSUE THREAD

**Issue by rconde01** [oleg-shilo/cs-script.vscode#3]
I followed the directions with no luck.

1) Installed vscode
2) Installed C# extension
3) Installed Mono Debug
4) Installed cs-script

I open my file...no intellisense.

**Comment by oleg-shilo** [comment]
But did you load the script? Press Ctrl+F7.

**Comment by rconde01** [comment]
aha!! Yes that gives me C# intellisense (sorry I missed that)...but i still don't get cs-script intellisense.

**Comment by oleg-shilo** [comment]
I know it's annoying but OmniSharp does not enable intellisense for an opened file and requires a workspace (folder) to be loaded. That's why you need to 'load' the script.  There is no really any technical reason for this and I was able to avoid "must be loaded" constrain in SublimeText. But it's very unlikely VSCode will ever change this. 
Though almost all the rest of the functionality can work without the workspace being loaded.

The doco says how to enable intellisense:
 
![image](https://user-images.githubusercontent.com/16729806/29394980-3cada1a2-8351-11e7-9576-eb6445c63376.png)

**Comment by oleg-shilo** [comment]
Start typing in the new line: `//css_` it should popup the autocomplete...

**Comment by rconde01** [comment]
ah...I didn't realize it needed the _ before matching...cool!! This is really cool!

**Comment by oleg-shilo** [comment]
Glad we sorted it out. :)
