### ISSUE TITLE
Features Request : Autocompletion & Format document

### ISSUE THREAD

**Issue by RexProg** [oleg-shilo/cs-script.vscode#7]
hi oleg-shilo
the features i really miss in VSCode is Autocompletion & Format document
OmniSharp doesn't work for me

**Comment by oleg-shilo** [comment]
The latest release has delivered the extension own Intellisense equivalent. 

[Release 1.4.0](https://github.com/oleg-shilo/cs-script.vscode/releases)
- Implemented Intellisense for standalone C# files:
  - Code completion
  - Go to definition
  - Hover/tooltip
  - Find all references
  - VS style of "Find all references" result in output panel
- Added VB.NET syntax support (Windows only)

It is very similar to the experience delivered by OmniSharp as it is based on Roslyn and relies on.

Though _Format document_ will be delivered in the very next release.

If you want to use CS-Script Intellisense you will need to open C# file alone with no workspace being loaded via open folder. You just need to wait a few seconds before VSCode loads all extensions and initializes Roslyn at startup.

Note that when VSCode has workspace loaded it completely takes control over the Intellisesnse. That is why CS-Script offers Intellisense only for stand alone C# files. 

> OmniSharp doesn't work for me.

It is strange as what CS-Script extension does for fallback intellisense is simply loads a C# workspace (folder with C# project) generated on fly.  After that CS-Script is not involved in intellisense support at all.

Can you send me the content of your CSSCRIPT-OMNISHARP folder so I can investigate?

![image](https://user-images.githubusercontent.com/16729806/38404726-73b1e69e-39af-11e8-9ba8-859543f6f1fc.png)

Just create a new script and then And load it as work space (Ctrl+F7):

![image](https://user-images.githubusercontent.com/16729806/38404792-d7a7d4e2-39af-11e8-90b4-5539b41e0619.png)

**Comment by RexProg** [comment]
Excellent ;D

**Comment by oleg-shilo** [comment]
Done. The latest release v1.5.1 contains all traditional Intellisense features including formatting.

**Comment by Falthazar** [comment]
Can you add an option to turn this off? I use "C# FixFormat" to format, since it has some extra options I like. Having them both active messes up formatting of C# files.
Also, it seems like the CSS formatter is removing indentation on blank lines?

**Comment by oleg-shilo** [comment]
Done in Release v1.5.5

**Comment by Falthazar** [comment]
Even with "cs-script.enable_code_formatting": false, it still seems to be causing an issue with C# Fix format. If I run "format document" it won't do anything. 
If I disable CS-Script it'll work, but I'm not sure if it's a bug on your end or fix format.

**Comment by oleg-shilo** [comment]
Yeah, implementing formatting via `DocumentFormattingEditProvider` is a much better option.  
Any extension can implement a provider for a given functionality (autocompletion, formatting, renaming). And if the extension decides not to handle the request at run time it simply returns `null` and other providers with process the request.

That's why CS-Script formatting is only engaged if no workspace loaded and `cs-script.enable_code_formatting` set to true. This way it does not interfere with any other cases when VSCode already does proper formatting (e.g. C# workspace).

I will still need to do an urgent release today to address some formatting artifacts  but of a completely different nature.
