### ISSUE TITLE
Add an option to hide "CS-Script: About" from the context menu

### ISSUE THREAD

**Issue by Knuds1** [oleg-shilo/cs-script.vscode#9]
How to reproduce:
When you right-click within a saved C# file you see "CS-Script: About" on the context menu.

Put it in the command palette instead.

![image](https://user-images.githubusercontent.com/5942707/39778527-76d56a04-52fe-11e8-84bb-6fb15a4acb00.png)

**Comment by oleg-shilo** [comment]
Fixed, will be available in the very next release.

---
Yes, it was a mistake.

The about command supposed to go to the `editor/title` instead of the `editor/context`.

![image](https://user-images.githubusercontent.com/16729806/39799483-bfbc60f2-53a7-11e8-8387-fef4789c0bd8.png)


Please mote that command palette already has this command included.
